USE [DSC Logistics]
GO
drop index a##pdate on a##pdate
drop index aadj on aadj
drop index acdestr on acde
drop index acmt on acmt
drop index acmtr on acmtr
drop index actl on actl
drop index actlezt on actl
drop index actlez1 on actl
drop index actlr on actlr
drop index adlhdr on adlhdr
drop index adllin on adllin
drop index adpwrk on adpwrk
drop index ageext on ageext
drop index agerptl1 on agerptf
drop index agerptl2 on agerptf
drop index age050f on age050f
drop index age050l1 on age050f
drop index age052f on age052f
drop index aitm on aitm
drop index aitmezt on aitm
drop index aitmr on aitmr
drop index aitmrx on aitmrx
drop index aitmw on aitmw
drop index aitmwx on aitmwx
drop index aitmx on aitmx
drop index albp on albp
drop index alcwrk on alcwrk
drop index aloc on aloc
drop index alocdtl on alocdtl
drop index anam on anam
drop index anamezt on anam
drop index arcust on arcust
drop index artd on artd
drop index artdr on artdr
drop index artdsfx on artd
drop index arth on arth
drop index arthflc on arth
drop index arthlf1 on arth
drop index arthlf2 on arth
drop index arthloc on arth
drop index arthp on arthp
drop index arthr on arthr
drop index arthstr on arthstr
drop index arxc on arxc
drop index arxf on arxf
drop index ashp on ashp
drop index ashpdat on ashpdat
drop index ashptsf on ashptsf
drop index asn856p on asn856p
drop index asts on asts
drop index astssum on astssum
drop index aststyp on asts
drop index aststypdtl on astsdtl
drop index a214 on a214
drop index a214app on a214app
drop index a214casc on a214
drop index a214crs on a214crs
drop index a214cty on a214cty
drop index a214dat on a214dat
drop index a214dlv on a214dlv
drop index a214doc on a214doc
drop index a214doc2 on a214
drop index a214drs on a214
drop index a214dst on a214dst
drop index a214iss on a214iss
drop index a214mbl on a214mbl
drop index a214nam on a214nam
drop index a214o on a214o
drop index a214pro on a214pro
drop index a214pro2 on a214
drop index a214ref on a214ref
drop index a214ref2 on a214
drop index a214sdc on a214
drop index a214sdco on a214o
drop index a214str on a214str
drop index bbwitm on bbwitm
drop index bcmt on bcmt
drop index bctl on bctl
drop index bitm on bitm
drop index bitmx on bitmx
drop index bldrefp on bldrefp
drop index bnam on bnam
drop index bob on bob
drop index bulktp on bulktp
drop index bulkwk on bulkwk
drop index bulkwkl1 on bulkwk
drop index bulkwkl2 on bulkwk
drop index bvasts on bvasts
drop index cacr on cacr
drop index cahr on cahr
drop index cahrcngj on cahrcngj
drop index cahrdrvj on cahrdrvj
drop index cahrshpj on cahrshpj
drop index caraud on caraud
drop index cart on cart
drop index ccmd on ccmd
drop index ccmdmfc on ccmd
drop index ccmdtrf on ccmdtrf
drop index ccmdtyp on ccmd
drop index ccon on ccon
drop index cconact on ccon
drop index ccst on ccst
drop index ccstad1 on ccst
drop index ccstcng on ccstcng
drop index ccstent on ccst
drop index ccstnam on ccst
drop index ccstpf on ccst
drop index ccstref on ccst
drop index ccstshp on ccstshp
drop index ccty on ccty
drop index cctynbr on ccty
drop index cctyrat on ccty
drop index cctyrtg on ccty
drop index cctyzip on ccty
drop index ccus on ccus
drop index ccusnam on ccus
drop index ccuspf on ccus
drop index ccus210 on ccus
drop index ccus214 on ccus
drop index ccvt on ccvt
drop index ccvtloc on ccvt
drop index cdemstr on cdemstr
drop index cdev on cdev
drop index cdevdrv on cdev
drop index cdsc on cdsc
drop index cdsctyp on cdsc
drop index cdst on cdst
drop index cdstcst on cdst
drop index cdup on cdup
drop index cemp on cemp
drop index cempall on cemp
drop index cempdrv on cempdrv
drop index cempdsn on cempdsn
drop index cempnam on cemp
drop index cempnbr on cemp
drop index cemptrm on cemp
drop index cempvbn on cemp
drop index ceqp on ceqp
drop index ceqpdrv on ceqp
drop index cfil on cfil
drop index cflm on cflm
drop index cfls on cfls
drop index cfrt on cfrt
drop index cfrtdat on cfrtdat
drop index cfrtinv on cfrt
drop index cfrtlst on cfrt
drop index cfrtque on cfrtque
drop index cfrtscp on cfrtscp
drop index cfrttsf on cfrt
drop index cfrt2 on cfrt2
drop index cfrt2x on cfrt2x
drop index cgdc on cgdc
drop index cgrd on cgrd
drop index cgrdgrd on cgrdgrd
drop index cgrdtrf on cgrdtrf
drop index cinstr on cinstr
drop index cinvdt on cinvdt
drop index cinvdtlf on cinvdt
drop index cinvhd on cinvhd
drop index cinvhdlf on cinvhdlf
drop index cinvwk on cinvwk
drop index citm on citm
drop index citx on citx
drop index citxcitx on citxcitx
drop index ciwkf on ciwkf
drop index ciwkg on ciwkg
drop index ciwkh on ciwkh
drop index clal on clal
drop index clbl on clbl
drop index clbl01 on clbl
drop index clbl02 on clbl
drop index clrt on clrt
drop index cmblchg on cmblchg
drop index cmblcmt on cmblcmt
drop index cmbldtl on cmbldtl
drop index cmblhdr on cmblhdr
drop index cmblhin on cmblhdr
drop index cmblpro on cmblpro
drop index cmid on cmid
drop index cmih on cmih
drop index cmihar# on cmih
drop index cmihart on cmih
drop index cmihcst on cmih
drop index cmihctt on cmih
drop index cmil on cmil
drop index cmlog on cmlog
drop index cmlogdt on cmlog
drop index cmlogsf on cmlog
drop index cmnl on cmnl
drop index cnam on cnam
drop index cnamnam on cnam
drop index cnbr on cnbr
drop index cnsctl on cnsctl
drop index cntwrk on cntwrk
drop index comments on comments
drop index compil on compil
drop index comstd on comstd
drop index coop on coop
drop index coravc on coravc
drop index coravd on coravd
drop index cositml1 on cositm
drop index cositml2 on cositm
drop index cositml3 on cositm
drop index cositml4 on cositm
drop index cospltl1 on cosplt
drop index cospltl2 on cosplt
drop index cospltl3 on cosplt
drop index cospltl4 on cosplt
drop index cospltl5 on cosplt
drop index cosreql1 on cosreq
drop index cosreql2 on cosreq
drop index cotc on cotc
drop index cpay on cpay
drop index cpaydptr on cpaydptr
drop index cpayle on cpayle
drop index cpaylf on cpaylf
drop index cper on cper
drop index cperfis on cper
drop index cpipd on cpipd
drop index cplc on cplc
drop index cplh on cplh
drop index cplhinv on cplh
drop index cplm on cplm
drop index cpln on cpln
drop index cplt on cplt
drop index cplx on cplx
drop index cprf on cprf
drop index cprfes on cprfes
drop index cprfloc on cprfloc
drop index cprfper on cprfper
drop index cprfz on cprfz
drop index cpsd on cpsd
drop index cpsh on cpsh
drop index crat on crat
drop index cratcls on crat
drop index crev on crev
drop index crevinv on crev
drop index crevper on crev
drop index crplbr on crplbr
drop index crtf on crtf
drop index csrc on csrc
drop index cstctl01 on tctl
drop index cstitm01 on titm
drop index cstm on cstm
drop index cstmnbr on cstm
drop index cstmshp on cstm
drop index cstr on cstr
drop index csts on csts
drop index cstsaud on csts
drop index cstslst on csts
drop index cstsmbil on cstsmbil
drop index cstspro on csts
drop index cstspro2 on csts
drop index cstsref on csts
drop index cststsf on cststsf
drop index csup on csup
drop index ctbl on ctbl
drop index cter on cter
drop index ctit on ctit
drop index ctktbl on ctktbl
drop index ctra on ctra
drop index ctrk on ctrk
drop index ctrm on ctrm
drop index ctrn on ctrn
drop index ctrnzip on ctrn
drop index cusaud on cusaud
drop index cusauddr on cusaud
drop index cusmfc on cusmfc
drop index cusmfclf on cusmfc
drop index cuswrk on cuswrk
drop index cvol on cvol
drop index cwitm on cwitm
drop index cxrf on cxrf
drop index cxrfctg on cxrf
drop index czip on czip
drop index c214 on c214
drop index dcnxlp on dcnxlp
drop index dcrtbl on dcrtbl
drop index ddup on ddup
drop index ddupdat on ddup
drop index ddupdoc on ddup
drop index ddupprg on ddup
drop index dfttbl on dfttbl
drop index ditm on ditm
drop index ditmloc on ditm
drop index ditmlocd on ditm
drop index ditmnam on ditm
drop index ditm2 on ditm2
drop index dlot on dlot
drop index dlotloc on dlot
drop index dlotlocd on dlot
drop index dlotnam on dlot
drop index dmricm01 on ricm
drop index dmrinb01 on rinb
drop index dmrlod01 on rlod
drop index dmrtsk01 on rtsk
drop index dmtinb01 on tinb
drop index dmtlcn01 on tlcn
drop index dncmt on dncmt
drop index dnctl on dnctl
drop index dnctll1 on dnctl
drop index dnctll2 on dnctl
drop index dnctll3 on dnctl
drop index dnitm on dnitm
drop index dnnam on dnnam
drop index doewrk on doewrk
drop index dpaccl1 on dpacc
drop index dpacd on dpacd
drop index dpaul1 on dpau
drop index dpaul2 on dpau
drop index dpaul3 on dpau
drop index dphldl1 on dphld
drop index dphldl2 on dphld
drop index dplcnl1 on dplcn
drop index dplcnl2 on dplcn
drop index dpomst on dpomst
drop index dpomstl1 on dpomst
drop index dprcl1 on dprc
drop index dprf on dprf
drop index dput026l1 on dput026f
drop index dput031l1 on dput031f
drop index dput061l1 on dput061f
drop index dput066l1 on dput066f
drop index dput066l2 on dput066f
drop index dput071l1 on dput071f
drop index dput076l1 on dput076f
drop index dput076l2 on dput076f
drop index dput076l3 on dput076f
drop index dput081l1 on dput081f
drop index dput086l1 on dput086f
drop index dput091l1 on dput091f
drop index dput096l1 on dput096f
drop index dpywrkm on dpywrkm
drop index draccl1 on dracc
drop index drvwrk on drvwrk
drop index drvwrk2 on drvwrk2
drop index dscoml01 on dscom
drop index dscsappf on dscsappf
drop index dslactxr01 on dspactxr
drop index dspdltmb on dspdltmb
drop index dspentad on dspentad
drop index dspifsent on dspifsent
drop index dspifspt on dspifspt
drop index dsppurgc on dsppurgc
drop index dsprefsh on dsprefsh
drop index dspwsctl on dspwsctl
drop index dsttbl on dsttbl
drop index dtaoutq on dtaoutq
drop index dtblcod on dtblcod
drop index dtbldsc on dtbldsc
drop index dtblk3 on dtbl
drop index dtbllsys on dtbllsys
drop index dtblmst on dtbl
drop index dtblmst1 on dtblmst1
drop index dtblmst2 on dtblmst2
drop index dwnbok on dwnbok
drop index dwndlv on dwndlv
drop index dwnldd on dwnldd
drop index dwnord on dwnord
drop index ediitm on ediitm
drop index edldl94701 on edldl94701
drop index edldl94702 on edpdl947
drop index edldl94703 on edldl94703
drop index edldl94704 on edpdl947
drop index edlgn94401 on edlgn94401
drop index edlgn94402 on edpgn944
drop index edlgn94403 on edlgn94403
drop index edlgn94404 on edpgn944
drop index edliit8801 on edliit8801
drop index edlkh82401 on edlkh82401
drop index edlmd94701 on edlmd94701
drop index edlmd94702 on edpmd947
drop index edlmd94703 on edlmd94703
drop index edlmd94704 on edpmd947
drop index edlmd94705 on edlmd94705
drop index edlmd94706 on edlmd94706
drop index edlopad01 on opad
drop index edlopad02 on edlopad02
drop index edlopad03 on edlopad03
drop index edlosvdx01 on edposvdx
drop index edlosvdx02 on edposvdx
drop index edl204d01 on edp204d
drop index edl204h01 on edp204h
drop index edl204h02 on edl204h02
drop index edl214dt01 on edl214dt01
drop index edl214dt02 on edp214dt
drop index edl214hd01 on edl214hd01
drop index edl214ms01 on edp214ms
drop index edl943dt01 on edp943dt
drop index edl943hd01 on edp943hd
drop index edpappfln on edpappfln
drop index edperrmsg on edperrmsg
drop index edperrmsl1 on edperrmsg
drop index edpexterr on edpexterr
drop index edpextl1 on edpextl1
drop index edpextl2 on edpextp
drop index edpidcd on edpidcd
drop index edpkrinb on edpkrinb
drop index edposvdx on edposvdx
drop index edposvdxh on edposvdxh
drop index edprlog1 on edprlog1
drop index edprpdfn on edprpdfn
drop index edpshpst on edpshpst
drop index edptasn on edptasn
drop index edptrnlog on edptrnlog
drop index edptrnml1 on edptrnml1
drop index edp204d on edp204d
drop index edp204h on edp204h
drop index edp214dt on edp214dt
drop index edp214hd on edp214hd
drop index edp214ms on edp214ms
drop index edp846d on edp846d
drop index edp846h on edp846h
drop index ei204d on ei204d
drop index ei204h on ei204h
drop index ei204i on ei204i
drop index ei204n on ei204n
drop index ei204s on ei204s
drop index ei204t on ei204t
drop index ei214d on ei214d
drop index ei214dac on ei214dac
drop index ei214d1 on ei214d
drop index ei214h on ei214h
drop index ei214hac on ei214hac
drop index ei214h1 on ei214h
drop index ei820d on ei820d
drop index ei820h on ei820h
drop index ei846h on ei846h
drop index ei947h on ei947h
drop index elbl on elbl
drop index elcn on elcn
drop index elcnl01 on elcnl01
drop index elcnl02 on elcnl02
drop index elcnl03 on elcn
drop index elcnl04 on elcn
drop index elcno on elcno
drop index elcntlj1 on elcntlj1
drop index elcntlj2 on elcntlj2
drop index elcntlj3 on elcntlj3
drop index elcntlj4 on elcntlj4
drop index elcn0tag on elcn0tag
drop index eltlcj01 on eltlcj01
drop index eltlcj02 on eltlcj02
drop index eltlcj03 on eltlcj03
drop index eltlcj04 on eltlcj04
drop index eltlcj05 on eltlcj05
drop index eltlj01 on eltlj01
drop index eltlj02 on eltlj02
drop index eltlj03 on eltlj03
drop index eltlj04 on eltlj04
drop index eltlj05 on eltlj05
drop index eltlj06 on eltlj06
drop index eltlj07 on eltlj07
drop index eltlj08 on eltlj08
drop index eltlj09 on eltlj09
drop index eltlj10 on eltlj10
drop index eltlj11 on eltlj11
drop index eltlj12 on eltlj12
drop index eltlj13 on eltlj13
drop index eltlj14 on eltlj14
drop index eltlj15 on eltlj15
drop index eltlj16 on eltlj16
drop index eltlj17 on eltlj17
drop index eltlj18 on eltlj18
drop index eltlj19 on eltlj19
drop index eltlj20 on eltlj20
drop index eltlj21 on eltlj21
drop index eltlj22 on eltlj22
drop index eltlj23 on eltlj23
drop index eltlj24 on eltlj24
drop index eltlj25 on eltlj25
drop index eltlj26 on eltlj26
drop index eltlj27 on eltlj27
drop index eltlj28 on eltlj28
drop index eltlj29 on eltlj29
drop index eltlj30 on eltlj30
drop index eltlj31 on eltlj31
drop index eltlj32 on eltlj32
drop index eltlj33 on eltlj33
drop index eltlj34 on eltlj34
drop index eltlj35 on eltlj35
drop index eltlj36 on eltlj36
drop index emaladrl1 on emaladrl1
drop index emaladrl2 on emaladrl2
drop index emaladrl3 on emaladrl3
drop index emaladrl4 on emaladrl4
drop index emaladrl5 on emaladrl5
drop index emaladrl6 on emaladrl6
drop index emaladrl7 on emaladrl7
drop index emaladrl8 on emaladrl8
drop index emaladrl9 on emaladrl9
drop index emalpgmp on emalpgmp
drop index emcarl01 on emcar
drop index emcarl02 on emcar
drop index emctnbat on emctnbat
drop index emctndoc on emctn
drop index emctndo2 on emctn
drop index emctnitm on emctn
drop index emctnit2 on emctn
drop index emctnlot on emctn
drop index emctnpst on emctnpst
drop index emctnseq on emctn
drop index emctnse2 on emctn
drop index emctnstr on emctn
drop index emctnst2 on emctn
drop index emctntag on emctn
drop index emctntg2 on emctn
drop index emitmbat on emitm
drop index emitmdcs on emitm
drop index emitmdoc on emitm
drop index emitmpkc on emitm
drop index emitmpke on emitm
drop index emitmsbd on emitm
drop index emitmseq on emitm
drop index emitmstr on emitm
drop index emlcnavl on emlcnavl
drop index emlcndoc on emlcn
drop index emlcnlot on emlcn
drop index emlcnl01 on emlcn
drop index emlcnl02 on emlcn
drop index emlcnpkl on emlcn
drop index emlcnstr on emlcnstr
drop index emlcntag on emlcn
drop index empwrk on empwrk
drop index emp0101 on emp0101
drop index em600pf on em600pf
drop index em900fl01 on em900f
drop index em900fl02 on em900f
drop index eofda on eofda
drop index eofdb on eofdb
drop index eofdc on eofdc
drop index eofdd on eofdd
drop index eofde on eofde
drop index eofdf on eofdf
drop index eofdg on eofdg
drop index eofdh on eofdh
drop index eofdi on eofdi
drop index eofdj on eofdj
drop index eofdk on eofdk
drop index eofdl on eofdl
drop index eofha on eofha
drop index eofhb on eofhb
drop index eofhc on eofhc
drop index eofhd on eofhd
drop index eofhe on eofhe
drop index eofhf on eofhf
drop index eomlg on eomlg
drop index eo210c on eo210c
drop index eo210d on eo210d
drop index eo210h on eo210h
drop index eo856d on eo856d
drop index eo856ditm on eo856d
drop index eo856h on eo856h
drop index eo990n on eo990n
drop index epud on epud
drop index epui on epui
drop index ermvm on ermvm
drop index esgd on esgd
drop index eshbl01 on eshb
drop index eshbl02 on eshbl02
drop index eshbl03 on eshbl03
drop index eshdl01 on eshd
drop index eshel01 on eshe
drop index eshjl01 on eshj
drop index esh201 on esh2
drop index esh202 on esh2
drop index esh203 on esh203
drop index esh204 on esh2
drop index esh205 on esh2
drop index esh206 on esh2
drop index esh207 on esh2
drop index esh210 on esh210
drop index esh214 on esh214
drop index esh215 on esh215
drop index esh216 on esh216
drop index esh217 on esh2
drop index esh218 on esh218
drop index esh220 on esh220
drop index esh225 on esh2
drop index esh226 on esh2
drop index esh401 on esh4
drop index esh402 on esh4
drop index esh406 on esh4
drop index esh408 on esh408
drop index esh501 on esh5
drop index esh502 on esh5
drop index esh503 on esh5
drop index esh504 on esh5
drop index esh505 on esh5
drop index esh506 on esh5
drop index esh507 on esh5
drop index esh508 on esh5
drop index esh509 on esh509
drop index esh510 on esh5
drop index esh511 on esh511
drop index esh512 on esh5
drop index esh513 on esh5
drop index esh514 on esh5
drop index esh515 on esh5
drop index esh516 on esh5
drop index esh517 on esh5
drop index esh518 on esh5
drop index esh519 on esh5
drop index esh520 on esh520
drop index esh521 on esh5
drop index esh523 on esh5
drop index esh524 on esh5
drop index esh525 on esh5
drop index esh526 on esh5
drop index esords on esords
drop index etbl on etbl
drop index evar on evar
drop index evardsc on evar
drop index exdtpf on exdtpf
drop index extdta on extdta
drop index exxcpp on exxcpp
drop index exxgrp on exllgpp
drop index exxmsg on exllmpp
drop index exxmsg2 on exllmpp
drop index fadd on fadd
drop index fahdr on fahdr
drop index fahdrlst on fahdr
drop index fahdrtsf on fahdrtsf
drop index fanetwrk on fanetwrk
drop index fbil on fbil
drop index fbilall on fbil
drop index fbildat on fbildat
drop index fbildatall on fbil
drop index fbildl on fbildl
drop index fbildst on fbil
drop index fbilhdr on fbilhdr
drop index fbilinv on fbil
drop index fbill2 on fbill2
drop index fbilord on fbil
drop index fbilpb on fbilpb
drop index fbilref on fbil
drop index fbilyymm on fbilyymm
drop index fbld on fbld
drop index fbldmbl on fbld
drop index fbldpdt on fbldpdt
drop index fcar on fcar
drop index fcarnam on fcar
drop index fcarscac on fcar
drop index fclt on fclt
drop index fcmt on fcmt
drop index fdlt on fdlt
drop index fdltbld on fdlt
drop index fdlto on fdlto
drop index fdmn on fdmn
drop index fdmnnbr on fdmn
drop index fdst on fdst
drop index fdstnam on fdst
drop index fdstscac on fdst
drop index fdstxrf on fdstxrf
drop index ffsc on ffsc
drop index fhhdr on fhhdr
drop index fhhdrlst on fhhdr
drop index fhhdrtsf on fhhdrtsf
drop index fhlt on fhlt
drop index fhltcar on fhlt
drop index fhltcasc on fhlt
drop index fhltcnm on fhltcnm
drop index fhltdat on fhlt
drop index fhlto on fhlto
drop index fhltpku on fhlt
drop index fhlttyp on fhlt
drop index fhm on fhm
drop index fhm2 on fhm2
drop index fhst on fhst
drop index fhststr on fhst
drop index fhzd on fhzd
drop index fh3 on fh3
drop index fh4 on fh4
drop index fh5 on fh5
drop index fh7 on fh7
drop index fh8 on fh8
drop index fixqt on fixqt
drop index fkptxrf on fkptxrf
drop index fltl on fltl
drop index fltlhdr on fltlhdr
drop index fltlhld on fltlhld
drop index fltltap on fltltap
drop index fltlzip on fltlzip
drop index fmbl on fmbl
drop index fmfc on fmfc
drop index fmfcdsc on fmfc
drop index fmfcxc on fmfcxc
drop index fosc on fosc
drop index fosclst on fosc
drop index fosctsf on fosctsf
drop index fpac on fpac
drop index fpay on fpay
drop index fpct on fpct
drop index fpyd on fpyd
drop index fpydloc on fpyd
drop index fpydmbl on fpyd
drop index fpydpro on fpyd
drop index fpyh on fpyh
drop index fpyhdat on fpyh
drop index fpyhinv on fpyh
drop index fpyhpol on fpyh
drop index fpyhsts on fpyh
drop index frat on frat
drop index frtdwn on frtdwn
drop index frttbl on frttbl
drop index fshl on fshl
drop index ftpctlf on ftpctlf
drop index ftpctlfs on ftpctlfs
drop index ftrn on ftrn
drop index ft1 on ft1
drop index ft1lst on ft1
drop index ft1tsf on ft1tsf
drop index ft2a on ft2a
drop index ft2s on ft2s
drop index ft3 on ft3
drop index ft6 on ft6
drop index ft7 on ft7
drop index fzip on fzip
drop index f47111 on f47111
drop index f47112 on f47112
drop index f47113 on f47113
drop index f47114 on f47114
drop index f550001 on f550001
drop index f550611 on f550611
drop index f60 on f60
drop index greetpf on greetpf
drop index gtbl on gtbl
drop index hact on hact
drop index hactap on hactap
drop index hactlf on hact
drop index hactpe on hact
drop index hactwrk on hactwrk
drop index hahr on hahr
drop index hanups on hanups
drop index hbil on hbil
drop index hbildat on hbil
drop index hcde on hcde
drop index hcmt on hcmt
drop index hcmtall on hcmt
drop index hcnl on hcnl
drop index hctl on hctl
drop index hctlall on hctl
drop index hctlbrk on hctl
drop index hctlbrkq on hctl
drop index hctlcasc on hctl
drop index hctlcrf on hctl
drop index hctlcrfq on hctl
drop index hctldst on hctldst
drop index hctlref on hctl
drop index hctlrefq on hctl
drop index hctlsid on hctl
drop index hctlstr on hctl
drop index hctlstrq on hctl
drop index hctl01 on hctl
drop index hdtl on hdtl
drop index hdtpar on hdtpar
drop index hesh201 on hesh2
drop index hesh401 on hesh4
drop index hesh501 on hesh5
drop index hexc on hexc
drop index hexcall on hexc
drop index hexr on hexr
drop index hexr2 on hexr2
drop index hgtbl on hgtbl
drop index hhdpar on hhdpar
drop index hht on hht
drop index hinb on hinb
drop index hitm on hitm
drop index hitmall on hitm
drop index hitmdocm on hitm
drop index hitmdocw on hitm
drop index hitml1 on hitm
drop index hitml2 on hitm
drop index hitmstr on hitm
drop index hitmx on hitmx
drop index hitx on hitx
drop index hiwkf on hiwkf
drop index hlbr on hlbr
drop index hlcnl01 on hlcn
drop index hlcnl02 on hlcn
drop index hlcnl03 on hlcn
drop index hlcnl04 on hlcn
drop index hlcnl05 on hlcn
drop index hlcnl06 on hlcn
drop index hlday on hlday
drop index hlod on hlod
drop index hlot on hlot
drop index hlotdwn on hlotdwn
drop index hlotxck on hlotxck
drop index hnam on hnam
drop index hncmt on hncmt
drop index hnctl on hnctl
drop index hnitm on hnitm
drop index hnnam on hnnam
drop index hobbld on hobbld
drop index hobdtl on hobdtl
drop index hobhdr on hobhdr
drop index hobpal on hobpal
drop index hosd92 on hosd92
drop index hpev on hpev
drop index hpevitm on hpev
drop index hpevplt on hpev
drop index hpevtag on hpev
drop index hpevtsk on hpev
drop index hpev04 on hpev
drop index hpev06 on hpev
drop index hsts on hsts
drop index hstsstd on hsts
drop index hstssts on hsts
drop index htsk on htsk
drop index hzddata on hzddata
drop index hzdtbl on hzdtbl
drop index h214 on h214
drop index h214lf on h214
drop index ibfm on ibfm
drop index iblacctm01 on ibpacctm
drop index iblgrpnd01 on ibpgrpnd
drop index iblgslbl01 on ibpgslbls
drop index iblgslbl02 on ibpgslbls
drop index iblgsxrf01 on ibpgsxrf
drop index iblinspq01 on ibpinspq
drop index iblinspq02 on ibpinspq
drop index iblminsp01 on ibpminsp
drop index iblraud01 on iblraud01
drop index iblsmart01 on ibpsmart
drop index iblsmart02 on ibpsmart
drop index ibltally on ibptally
drop index ibltinsp01 on ibptinsp
drop index ibltrins01 on ibptrins
drop index ibmrmtwtr on ibmrmtwtr
drop index ibpacctm on ibpacctm
drop index ibpgslbls on ibpgslbls
drop index ibpgsxrf on ibpgsxrf
drop index ibpinbex on ibpinbex
drop index ibpinspq on ibpinspq
drop index ibptally on ibptally
drop index ibptrins on ibptrins
drop index ib214 on ib214
drop index iclcaud01 on icpcaud
drop index iclcaud02 on icpcaud
drop index iclcntbc01 on iclcntbc01
drop index iclcntbc02 on iclcntbc02
drop index iclcntbc03 on iclcntbc03
drop index iclhplt01 on icphplt
drop index iclhplt02 on icphplt
drop index icliaud01 on icpiaud
drop index icliaud02 on icpiaud
drop index icliplt01 on icpiplt
drop index iclireq01 on icpireq
drop index iclpmuss01 on icppmusst
drop index iclpmuss02 on icppmusst
drop index iclqahl01 on icpqahl
drop index iclqahl02 on icpqahl
drop index iclqain01 on icpqain
drop index iclqain02 on icpqain
drop index iclqain03 on icpqain
drop index iclqain04 on icpqain
drop index iclqaud01 on icpqaud
drop index iclqaud02 on icpqaud
drop index iclqaud03 on icpqaud
drop index iclqaud04 on icpqaud
drop index iclqaud05 on icpqaud
drop index iclqaud06 on icpqaud
drop index iclqerr01 on icpqerr
drop index iclqplt01 on icpqplt
drop index iclqpnd01 on icpqpnd
drop index iclqpnd02 on icpqpnd
drop index iclqpnd03 on icpqpnd
drop index iclqpnd04 on icpqpnd
drop index iclqreq01 on icpqreq
drop index iclqreq02 on icpqreq
drop index iclqreq03 on icpqreq
drop index iclqreq04 on icpqreq
drop index iclqrtn01 on icpqrtn
drop index iclqrtn02 on icpqrtn
drop index iclqxml101 on icpqxml1
drop index iclqxml201 on icpqxml2
drop index iclqxml202 on icpqxml2
drop index icltaud01 on icptaud
drop index icpcntbck on icpcntbck
drop index icphldsum on icphldsum
drop index icphldxrf on icphldxrf
drop index icpinvst on icpinvst
drop index icplotbk on icplotbk
drop index icpmasdlt on icpmasdlt
drop index icpqasnfx on icpqasnfx
drop index icpqasnfxe on icpqasnfxe
drop index icpqasnfxo on icpqasnfxo
drop index icptbmplt on icptbmplt
drop index iinv on iinv
drop index imfa on imfa
drop index imnt on imnt
drop index inbdst on inbdst
drop index inbdstlm on inbdst
drop index inbdstl1 on inbdst
drop index inrinb01 on rinb
drop index inrosd01 on rosd
drop index intinb01 on tinb
drop index invhdr on invhdr
drop index invhdrl1 on invhdr
drop index invhdrl2 on invhdr
drop index invsum on invsum
drop index invsuml1 on invsum
drop index invwrk on invwrk
drop index invwrkl1 on invwrk
drop index invwrkl2 on invwrk
drop index invwrkl3 on invwrk
drop index iodrl01 on iodrp
drop index ipacd on ipacd
drop index ipach on ipach
drop index ipod on ipod
drop index ipoh on ipoh
drop index iprf on iprf
drop index iprt on iprt
drop index iravc on iravc
drop index iravd on iravd
drop index iravh on iravh
drop index irec on irec
drop index irectw on irectw
drop index irec00fv1 on irec00fv1
drop index irec00l1 on irec00f
drop index irec01fv1 on irec01fv1
drop index irec01l1 on irec01f
drop index irec01rfl1 on irec01frf
drop index irec01twl1 on irec01ftw
drop index irec02l1 on irec02f
drop index irec02rfl1 on irec02frf
drop index irec02twl1 on irec02ftw
drop index irwkf on irwkf
drop index isbih on isbih
drop index istsc on istsc
drop index istscl01 on istsc
drop index istsd on istsd
drop index istsdl01 on istsd
drop index istsh on istsh
drop index istshl01 on istsh
drop index istshl02 on istsh
drop index istshl03 on istsh
drop index istshscc on istsh
drop index istshsid on istsh
drop index istsr on istsr
drop index istsrl01 on istsr
drop index istsx on istsx
drop index istsxl01 on istsx
drop index itdw2cas on itmdw2
drop index itdw2cng on itmdw2x
drop index itdw2dat on itmdw2x
drop index itdw2ord on itmdw2
drop index itdw2plt on itmdw2
drop index itdw2wgt on itmdw2
drop index itmcdel1 on itmcde
drop index itmcdel2 on itmcde
drop index itmdwn4 on itmdwn4
drop index itmdw2 on itmdw2
drop index itmdw2x on itmdw2x
drop index itmdw3 on itmdw3
drop index itmd888l1 on itmd888
drop index itmh888l1 on itmh888l1
drop index itmh888l2 on itmh888
drop index itmr on itmr
drop index itmtrn on itmtrn
drop index itmtrnlf on itmtrn
drop index itndc on itndc
drop index itndcedt on itndc
drop index itndd on itndd
drop index itndh on itndh
drop index itndhedt on itndhedt
drop index itndherr on itndherr
drop index itndhst on itndh
drop index iwitm on iwitm
drop index i214h on i214h
drop index i820d on i820d
drop index i820h on i820h
drop index i820he on i820he
drop index i820hs on i820h
drop index i864c on i864c
drop index i864d on i864d
drop index i864h on i864h
drop index i943c on i943c
drop index i943d on i943d
drop index i943h on i943h
drop index i943wib on i943w
drop index jeeplibl on jeeplibl
drop index jelcnwhdt on jelcnwhdt
drop index jjedi on jjedi
drop index jlcnara on jlcnara
drop index job101al1 on job101a
drop index job101al2 on job101a
drop index jrinbdr3 on jrinbdr3
drop index jrnfile on jrnfile
drop index jrnfile2 on jrnfile2
drop index jrnmaster1 on jrnmaster1
drop index jrnmaster2 on jrnmaster2
drop index jrotbdr3 on jrotbdr3
drop index jtlcnaf on jtlcnaf
drop index jtlcnaf1 on jtlcnaf1
drop index jtlcnaf2 on jtlcnaf2
drop index jtlcnaf3 on jtlcnaf3
drop index jtlcnat on jtlcnat
drop index jtlcnat1 on jtlcnat1
drop index jtlcnat2 on jtlcnat2
drop index jtlcnat3 on jtlcnat3
drop index jtlcnef on jtlcnef
drop index jtlcnef1 on jtlcnef1
drop index jtlcnef2 on jtlcnef2
drop index jtlcnef3 on jtlcnef3
drop index jtlcnem on jtlcnem
drop index jtlcnem1 on jtlcnem1
drop index jtlcnem2 on jtlcnem2
drop index jtlcnem3 on jtlcnem3
drop index jtlcnia on jtlcnia
drop index jtlcnif on jtlcnif
drop index jtlcninb on jtlcninb
drop index jtlcnla on jtlcnla
drop index jtlcnlf on jtlcnlf
drop index jtlcnoa on jtlcnoa
drop index jtlcnof on jtlcnof
drop index jtlcnpa on jtlcnpa
drop index jtlcnpf on jtlcnpf
drop index jtpkortm on jtpkortm
drop index jwitm on jwitm
drop index jwtlcn on jwtlcn
drop index jwtlcnpl on jwtlcnpl
drop index jwtlcnsloc on jwtlcnsloc
drop index keypoint on keypoint
drop index kflodwitm on kflodwitm
drop index kitsl01 on kits
drop index knnqe1 on knnqe1
drop index knnqe2 on knnqe2
drop index lbldexl1 on lbldex
drop index lblexcl1 on lblexc
drop index lblinfl1 on lblinf
drop index lblinfl2 on lblinf
drop index lblinfl3 on lblinf
drop index lblinfl4 on lblinf
drop index lblinfl5 on lblinf
drop index lblinfl6 on lblinf
drop index lbloutl1 on lblout
drop index lbloutl2 on lblout
drop index lbloutl3 on lblout
drop index lbloutl4 on lblout
drop index lbloutl5 on lblout
drop index lblrrcl1 on lblrrc
drop index lblrrcl2 on lblrrc
drop index lblrrcl3 on lblrrc
drop index lblsrcl1 on lblsrc
drop index lblsrcl2 on lblsrc
drop index lblsrcl3 on lblsrc
drop index lbltrkl1 on lbltrk
drop index lbltrkl2 on lbltrk
drop index lbltrkl3 on lbltrk
drop index lbltrkl4 on lbltrk
drop index lblxrfl1 on lblxrf
drop index lbrxtra on lbrxtra
drop index lbrxtrp on lbrxtrp
drop index lcom on lcom
drop index ldswitm on ldswitm
drop index lemp on lemp
drop index lempbld on lemp
drop index lempnam on lemp
drop index lempnbr on lempnbr
drop index lempsft on lempsft
drop index lempwhs on lempwhs
drop index libs on libs
drop index linb on linb
drop index linbdep on linb
drop index linbitm on linb
drop index litm on litm
drop index litmara on litm
drop index litmque on litm
drop index liwkf on liwkf
drop index lmgrb on lmgrb
drop index lmpcodes on lmpcodes
drop index lmsomit on lmsomit
drop index location on location
drop index locshr on locshr
drop index loctbl on loctbl
drop index loc204 on loc204
drop index lodchg on lodchg
drop index lodstp on lodstp
drop index lodwitm on lodwitm
drop index lotcnvp on lotcnvp
drop index lspcl1 on lspc
drop index lstr on lstr
drop index lstrara on lstr
drop index ltlc on ltlc
drop index ltlwk2p on ltlwk2p
drop index l8lvarpf on l8lvarpf
drop index mbll01 on mblp
drop index mbll02 on mblp
drop index mbll03 on mblp
drop index metbl on metbl
drop index mlbl on mlbl
drop index mlcdl01 on mlcd
drop index mlog on mlog
drop index mloggrp on mloggrp
drop index mlogint on mlogint
drop index mlogloc on mlog
drop index mnbdpo on mnbdpo
drop index mnccde on mnccde
drop index mncclf on mnccde
drop index mncppk on mncppk
drop index mndwnp on mndwnp
drop index mnfrct on mnfrct
drop index mnmfmt on mnmfmt
drop index mnporf on mnporf
drop index mnprds on mnprds
drop index mnreff on mnreff
drop index mnsced on mnsced
drop index mnslwk on mnslwk
drop index mnslwkd on mnslwk
drop index mnslwkdl on mnslwk
drop index mntdta on mntdta
drop index mnupdf on mnupdf
drop index mpgm on mpgm
drop index mpgmdsc on mpgm
drop index mrgz on mrgz
drop index mrgzpty on mrgz
drop index mtbl on mtbl
drop index mtxt on mtxt
drop index mtxtmnu on mtxtmnu
drop index nabitm on nabitm
drop index nbrcv on nbrcv
drop index newcrat on newcrat
drop index oaavd on oaavd
drop index oaavdl01 on oaavd
drop index oaavh on oaavh
drop index oaavhdat on oaavh
drop index oaavhdoc on oaavh
drop index oaavhref on oaavh
drop index oaavhtrn on oaavh
drop index oaavhtsf on oaavh
drop index obarv on obarv
drop index obbld on obbld
drop index obbldl01 on obbld
drop index obbldl01o on obbldo
drop index obbldo on obbldo
drop index obcase on obcase
drop index obcasel1 on obcase
drop index obcnl01 on obcn
drop index obcnl01o on obcno
drop index obdoor on obdoor
drop index obdoorl1 on obdoor
drop index obdtl on obdtl
drop index obdtll01 on obdtl
drop index obdtll02 on obdtl
drop index obdtll03 on obdtl
drop index obdtll04 on obdtl
drop index obdtll05 on obdtl
drop index obdtll06 on obdtl
drop index obdtll07 on obdtl
drop index obdtll08 on obdtl
drop index obdtll09 on obdtl
drop index obdtll09o on obdtlo
drop index obdtll10 on obdtl
drop index obdtll11 on obdtl
drop index obdtll12 on obdtl
drop index obdtlo on obdtlo
drop index obdtl09 on obdtl
drop index obhdr on obhdr
drop index obhdrl01 on obhdr
drop index obhdrl02 on obhdr
drop index obhdrl03 on obhdr
drop index obhdrl04 on obhdrl04
drop index obhdro on obhdro
drop index oblasnlb01 on obpasnlb
drop index oblasnlb02 on obpasnlb
drop index oblasnlb03 on obpasnlb
drop index oblasnlb04 on obpasnlb
drop index oblasnlb05 on obpasnlb
drop index oblasnlb06 on obpasnlb
drop index oblasnlb07 on obpasnlb
drop index oblasnlb08 on obpasnlb
drop index oblasnlb09 on obpasnlb
drop index oblasnlb10 on obpasnlb
drop index oblcdl on oblcdl
drop index oblldcon01 on obpldcon
drop index oblldcon02 on obpldcon
drop index oblldcon2o on obpldcono
drop index oblmbwrk01 on obpmbwrk
drop index oblmbwrk02 on obpmbwrk
drop index oblmnaud01 on obpmnaud
drop index oblmnerr01 on obpmnerr
drop index oblmstbl01 on obpmstbl
drop index oblmstbl02 on obpmstbl
drop index oblmstbl03 on obpmstbl
drop index oblmstbl04 on obpmstbl
drop index oblmstbl05 on obpmstbl
drop index oblnasn01 on obpnasn
drop index oblnasn02 on obpnasn
drop index oblnasn03 on obpnasn
drop index oblnasn04 on oblnasn04
drop index oblnasn05 on oblnasn05
drop index oblnasn06 on obpnasn
drop index oblnasn07 on obpnasn
drop index oblobex01 on obpobex
drop index oblod on oblod
drop index oblpardt01 on obppardt
drop index oblpardt02 on obppardt
drop index oblpigps01 on obppigps
drop index oblpigps02 on obppigps
drop index oblpkldd01 on obppkldd
drop index oblpkldd02 on obppkldd
drop index oblpkldd03 on oblpkldd03
drop index oblpkldd04 on oblpkldd04
drop index oblpkldd05 on obppkldd
drop index oblpkldd06 on oblpkldd06
drop index oblpkldd07 on obppkldd
drop index oblpkldd08 on obppkldd
drop index oblpkldd09 on obppkldd
drop index oblpkldd10 on oblpkldd10
drop index oblpkldd11 on obppkldd
drop index oblpkldd12 on oblpkldd12
drop index oblpkldd13 on oblpkldd13
drop index oblpkldd14 on oblpkldd14
drop index oblpkldd15 on oblpkldd15
drop index oblplque01 on oblplque01
drop index oblplque02 on oblplque02
drop index oblsmsau01 on obpsmsau
drop index oblsmxrf01 on obpsmxrf
drop index oblsparh01 on obpsparh
drop index oblspari01 on obpspari
drop index oblspari02 on obpspari
drop index obltansv01 on obptansv
drop index obltlo01 on obltlo01
drop index obltrlms01 on obltrlms01
drop index obmsg on obmsg
drop index obnxt on obnxt
drop index obpal on obpal
drop index obpall01 on obpal
drop index obpall02 on obpall02
drop index obpall03 on obpall03
drop index obpall04 on obpall04
drop index obpall05 on obpall05
drop index obpall06 on obpall06
drop index obpall07 on obpall07
drop index obpall08 on obpall08
drop index obpall09 on obpal
drop index obpall10 on obpall10
drop index obpall11 on obpall11
drop index obpall12 on obpall12
drop index obpall13 on obpal
drop index obpall14 on obpall14
drop index obpall15 on obpal
drop index obpall16 on obpal
drop index obpall17 on obpal
drop index obpall18 on obpal
drop index obpall19 on obpal
drop index obpall20 on obpall20
drop index obpalo on obpalo
drop index obpalx on obpalx
drop index obpasnlb on obpasnlb
drop index obpasnlh on obpasnlh
drop index obpfrttr on obpfrttr
drop index obphazms on obphazms
drop index obpldcon on obpldcon
drop index obpldcono on obpldcono
drop index obpmbwrk on obpmbwrk
drop index obpmstbl on obpmstbl
drop index obpmstblbk on obpmstblbk
drop index obpmstblwk on obpmstblwk
drop index obpnasn on obpnasn
drop index obpn856 on obpn856
drop index obpobex on obpobex
drop index obpobexh on obpobexh
drop index obpobexo on obpobexo
drop index obpobopt on obpobopt
drop index obpordrl on obpordrl
drop index obppardt on obppardt
drop index obpparhd on obpparhd
drop index obpparlb on obpparlb
drop index obpparlg on obpparlg
drop index obpparsm on obpparsm
drop index obppcldw on obppcldw
drop index obppkldh on obppkldh
drop index obppklst on obppklst
drop index obpplque on obpplque
drop index obpsmxrf on obpsmxrf
drop index obpsoutq on obpsoutq
drop index obpsparc on obpsparc
drop index obpspard on obpspard
drop index obpsparh on obpsparh
drop index obpspari on obpspari
drop index obpsparp on obpsparp
drop index obptlo on obptlo
drop index obptrlms on obptrlms
drop index obpuccpr on obpuccpr
drop index obpuccsn on obpuccsn
drop index obtot on obtot
drop index obtotl01 on obtot
drop index ochpd on ochpd
drop index ochpd01 on ochpd
drop index ochph on ochph
drop index ochphmds on ochphmds
drop index octbl on octbl
drop index of945p on of945p
drop index ogc204 on ogc204
drop index ogd204 on ogd204
drop index ogd204p on ogd204
drop index ogd204s on ogd204
drop index ogd204w on ogd204
drop index ogd204x on ogd204x
drop index ogh204 on ogh204
drop index ogn204 on ogn204
drop index oinvd on oinvd
drop index oinvh on oinvh
drop index oivcd on oivcd
drop index oivcdl01 on oivcd
drop index oivch on oivch
drop index oivchtsf on oivch
drop index oivd on oivd
drop index omf204 on omf204
drop index omh204 on omh204
drop index omh204p on omh204
drop index omh204r on omh204
drop index omh204s on omh204s
drop index ootbl on ootbl
drop index opad on opad
drop index opadhdr on opadhdr
drop index opjctlob on opjctlob
drop index opndwn on opndwn
drop index opod on opod
drop index opoh on opoh
drop index oprf on oprf
drop index opt on opt
drop index oqlst on oqlst
drop index oravc on oravc
drop index oravcl01 on oravc
drop index oravd on oravd
drop index oravditm on oravd
drop index oravdw on oravdw
drop index oravh on oravh
drop index oravhdat on oravh
drop index oravhdoc on oravh
drop index oravhref on oravh
drop index oravhtrn on oravh
drop index oravhtsf on oravh
drop index ordspl on ordspl
drop index ordspl1 on ordspl
drop index ordtbl on ordtbl
drop index ordtot on ordtot
drop index ordtotl1 on ordtot
drop index ordtotl2 on ordtot
drop index ordwrk on ordwrk
drop index orefpgm on oref
drop index orlth on orlth
drop index osavc on osavc
drop index osavcc on osavcc
drop index osavcl01 on osavc
drop index osavcp on osavcp
drop index osavcpp on osavcpp
drop index osavd on osavd
drop index osavdc on osavdc
drop index osavdl01 on osavd
drop index osavdl02 on osavd
drop index osavdl04 on osavd
drop index osavdl05 on osavd
drop index osavdpp on osavdpp
drop index osavdw on osavdw
drop index osavdw2 on osavdw2
drop index osavdw4 on osavdw4
drop index osavhdat on osavh
drop index osavhlnk on osavh
drop index osavhpp on osavhpp
drop index osavhref on osavh
drop index osavhtrn on osavh
drop index osavhtsf on osavh
drop index osavs on osavs
drop index oslxdxref2 on ospxdxref
drop index ospxdxref on ospxdxref
drop index ostsall on ostsall
drop index ostsh on ostsh
drop index ostshdoc on ostsh
drop index ostshgen on ostsh
drop index ostshhst on ostsh
drop index ostshlst on ostsh
drop index ostshmbl on ostsh
drop index ostshpro on ostsh
drop index ostshref on ostsh
drop index ostshtpl on ostshtpl
drop index ostshtsf on ostsh
drop index ostsh2 on ostsh2
drop index ostsx on ostsx
drop index oswedis on oswedis
drop index osweiot on osweiot
drop index oswtsf on osweiot
drop index otdtl on otdtl
drop index otdtlref on otdtl
drop index othdr on othdr
drop index othdrmbl on othdr
drop index othdrsca on othdr
drop index otrtdl01 on otrtd
drop index otrtdl02 on otrtd
drop index otrthl01 on otrth
drop index otschw on otschw
drop index ot001pf on ot001pf
drop index ot011wrk on ot011wrk
drop index outqctl on outqctl
drop index o204c on o204c
drop index o204d on o204d
drop index o204h on o204h
drop index o204hdat on o204hdat
drop index o204htsf on o204h
drop index o846d on o846d
drop index o846h on o846h
drop index o856d on o856d
drop index o856ditm on o856d
drop index o856dsrl on o856d
drop index o856ducc on o856d
drop index o856dx on o856dx
drop index o856h on o856h
drop index o856hchp on o856hchp
drop index o856hcng on o856h
drop index o856hmds on o856hmds
drop index o856hoch on o856hoch
drop index o856hrc on o856hrc
drop index o856hrcx on o856hrcx
drop index o856href on o856href
drop index o856hsav on o856hsav
drop index o856hstr on o856hstr
drop index o945d on o945d
drop index o945dxx on o945dxx
drop index o945h on o945h
drop index o945p on o945p
drop index pacc on pacc
drop index pacc10 on pacc10
drop index pacn on pacn
drop index palc on palc
drop index par on pa
drop index pau on pa
drop index paydats on paydats
drop index paysmdt on paysum
drop index paysum on paysum
drop index paysumle on paysumle
drop index paysumlf on paysumlf
drop index paysump on paysump
drop index pcag on pcag
drop index pcagitm on pcag
drop index pcagstr on pcag
drop index pcfg on pcfg
drop index pckstl1 on pckst
drop index pckwrk on pckwrk
drop index pcl on pc
drop index pcmt on pcmt
drop index pcode1l1 on pcode1f
drop index pcode2l1 on pcode2f
drop index pcode3f on pcode3f
drop index pcon on pcon
drop index pcr on pc
drop index pctbl on pctbl
drop index pctl on pctl
drop index pctlmbr on pctl
drop index pcu on pc
drop index pdfainv on pdfa
drop index pdoc on pdoc
drop index pdtl on pdtl
drop index pdtlitm on pdtl
drop index pdtllcn on pdtl
drop index pdtlltq on pdtl
drop index pdtltag on pdtl
drop index pdup on pdup
drop index perdta on perdta
drop index petemp on petemp
drop index pgmfile on pgmfile
drop index phst on phst
drop index pidb on pidb
drop index pidp on pidp
drop index pinv on pinv
drop index pinvitm on pinv
drop index pinvlcn on pinv
drop index pinvlot on pinv
drop index pinvl8d on pinvl8d
drop index pipc on pipc
drop index pir on pi
drop index pitblcod on pitbl
drop index pitblmst1 on pitbl
drop index pitblmst2 on pitbl
drop index pitm on pitm
drop index pitx on pitx
drop index pjbc on pjbc
drop index pklfrovr01 on pkpfrovr
drop index pklfrshp01 on pkpfrshp
drop index pklspchd01 on pkpspchd
drop index pklspchd02 on pkpspchd
drop index pkpspchd on pkpspchd
drop index pkpspmsg on pkpspmsg
drop index pkpspmst on pkpspmst
drop index plcn on plcn
drop index plcndat on plcn
drop index plcnemp on plcn
drop index pltercd on pltercd
drop index pltwrk on pltwrk
drop index pmagdtl1 on pmagdtpf
drop index pmagfdsc on pmagfdsc
drop index pmagfdw1 on pmagfdwk
drop index pmagfdw2 on pmagfdwk
drop index pmaghdl1 on pmaghdpf
drop index pmagqtl1 on pmagqtpf
drop index pmfile2 on pmfile2
drop index pminv on pminv
drop index pminvall on pminv
drop index pmqadtl1 on pmqadtpf
drop index pmqafdsc on pmqafdsc
drop index pmqafdw1 on pmqafdwk
drop index pmqahdl1 on pmqahdpf
drop index pmqaqtl1 on pmqaqtpf
drop index pmrdefp on pmrdefp
drop index pmxl1 on pmx
drop index pmxref on pmxref
drop index pmxrefl1 on pmxref
drop index pm0101 on pm0101
drop index pm0301 on pm0301
drop index pm0416 on pm0416
drop index pm0746 on pm0746
drop index pm2416 on pm2416
drop index pm6009 on pm6009
drop index pm6010 on pm6010
drop index pm6013 on pm6013
drop index pm6310 on pm6310
drop index pm7416 on pm7416
drop index pnrokit on pnro
drop index pnrosam on pnro
drop index pnrosamnc on pnrosamnc
drop index pnrslsdi on pnrs
drop index pnrslsds on pnrs
drop index pnrsplti on pnrs
drop index pnrssam on pnrs
drop index pnrssam2 on pnrs
drop index pnrtlssi on pnrtlssi
drop index pnrtsam on pnrt
drop index pnrtsmer on pnrtsmer
drop index pooldir on pooldir
drop index pooldirx on pooldirx
drop index pord on pord
drop index pordlog on pord
drop index pordref on pord
drop index pordref1 on pord
drop index ppjc on ppjc
drop index pptc on pptc
drop index preflf on pref
drop index prefpgm on pref
drop index prefpgm1 on pref
drop index prfwkl on prfwkp
drop index prfwkp on prfwkp
drop index prgoutqdta on prgoutqdta
drop index prodta on prodta
drop index prpl on prpl
drop index prpllcn on prpl
drop index prpltag on prpl
drop index prpltim on prpl
drop index psug on psug
drop index psum on psum
drop index ptag on ptag
drop index ptbl on ptbl
drop index ptkl on ptkl
drop index pvar on pvar
drop index pvarabs on pvar
drop index pvarhed on pvar
drop index pvarset on pvar
drop index pver on pver
drop index pwtran on pwtran
drop index pznl on pznl
drop index pznllcn on pznl
drop index pznllvl on pznl
drop index pzns on pzns
drop index pznslf1 on pzns
drop index pzon on pzon
drop index p1r on p1
drop index p1u on p1
drop index p2b on p2
drop index p2c on p2
drop index p2l on p2
drop index p2r on p2
drop index p2s on p2
drop index p2u on p2
drop index p2z on p2
drop index p3c on p3
drop index p3d on p3
drop index p3r on p3
drop index p3u on p3
drop index p5u on p5
drop index qarl1 on qarp
drop index qarl2 on qarp
drop index qarpltl1 on qarplt
drop index qarreql1 on qarreq
drop index rase on rase
drop index rasedat on rase
drop index rasedoc on rase
drop index raseloc on rase
drop index rasetag on rase
drop index rasm on rasm
drop index rasp on rasp
drop index raspdoc on rasp
drop index rawn on rawn
drop index rbal on rbal
drop index rbbd on rbbd
drop index rbbddoc on rbbd
drop index rbpk on rbpk
drop index rcar on rcar
drop index rcarx on rcarx
drop index rcas on rcas
drop index rcod on rcod
drop index rctbl on rctbl
drop index rdis on rdis
drop index rdrwa on rdrwa
drop index rdrwacmp on rdrwa
drop index rdrwadlt on rdrwadlt
drop index rdrwaupd on rdrwa
drop index relcfitem on repcftlel
drop index relcfloc on repcftlel
drop index relcftle03 on repcftlel
drop index relrpshpty on reprpsh
drop index relrpshusr on relrpshusr
drop index relrpsh01 on reprpsh
drop index relrpsh02 on reprpsh
drop index relrpsh03 on reprpsh
drop index relwpshais on relwpshais
drop index relwpshbwd on repwpsh
drop index relwpshitm on repwpsh
drop index relwpshjep on repwpsh
drop index relwpshloc on repwpsh
drop index relwpshlsi on repwpsh
drop index relwpshpkl on repwpsh
drop index relwpshpla on relwpshpla
drop index relwpshpld on relwpshpld
drop index relwpshrev on repwpsh
drop index relwpshslk on relwpshslk
drop index relwpshtag on repwpsh
drop index relwpshusr on repwpsh
drop index remp on remp
drop index rempfst on remp
drop index rempini on remp
drop index remplst on remp
drop index remp2l1 on remp2
drop index reorglf on reorg
drop index reqp on reqp
drop index reqpjep on reqp
drop index reqpjlm on reqp
drop index reqpvin on reqp
drop index rety on rety
drop index retydsc on rety
drop index retyx on retyx
drop index rfdp2l01 on rfdp2
drop index rfop on rfop
drop index rfop2 on rfop2
drop index rfrpev01 on rpev
drop index rfstvday on rfstvday
drop index rhld on rhld
drop index rhldl1 on rhld
drop index rhldl2 on rhld
drop index ricm on ricm
drop index rifm on rifm
drop index rifmnew on rifm
drop index rinb on rinb
drop index rinbbil on rinb
drop index rinbbild on rinb
drop index rinbdor on rinb
drop index rinbdr2 on rinb
drop index rinbent on rinb
drop index rinblod on rinb
drop index rinblodx on rinb
drop index rinbsch on rinb
drop index rinbschi on rinb
drop index riop on riop
drop index riopx on riopx
drop index riop2 on riop2
drop index riop3itm on riop3
drop index riop3seq on riop3
drop index ritm on ritm
drop index ritmbat on ritm
drop index ritmbato on ritm
drop index ritmbloc on ritm
drop index ritmbt3 on ritm
drop index ritmdoc on ritmdoc
drop index ritmdsq on ritm
drop index ritmitm on ritm
drop index ritmpck on ritmpck
drop index ritmplc on ritm
drop index ritmpltw on ritm
drop index ritmsal on ritmsal
drop index ritmseq on ritm
drop index ritmsub on ritm
drop index ritmwgt on ritm
drop index rjcd on rjcd
drop index rjcdstg on rjcd
drop index rjrdata on rjrdata
drop index rjrday on rjrday
drop index rjrdayl2 on rjrday
drop index rjrdtal3 on rjrdata
drop index rjrtitm on rjrtitm
drop index rjrups on rjrups
drop index rlbr on rlbr
drop index rlbrdat on rlbr
drop index rlbrm on rlbrm
drop index rlbrpcs on rlbrpcs
drop index rlbrprf on rlbr
drop index rlbrstr on rlbr
drop index rlbrtsk on rlbr
drop index rlcn on rlcn
drop index rlcnh on rlcnh
drop index rlod on rlod
drop index rlodbld on rlod
drop index rlodcio on rlodcio
drop index rlodpete on rlod
drop index rlodttm on rlod
drop index rlog on rlog
drop index rlogapl on rlog
drop index rlrp on rlrp
drop index rlrpstr on rlrp
drop index rmrg on rmrg
drop index rmtshr on rmtshr
drop index roph on roph
drop index ropn on ropn
drop index ropninl on ropninl
drop index ropnpck on ropnpck
drop index rosd on rosd
drop index rotb on rotb
drop index rotbdoc on rotb
drop index rotbdor on rotb
drop index rotbent on rotb
drop index rotblod on rotb
drop index rotbmbl on rotb
drop index rotbsch on rotb
drop index rpev on rpev
drop index rpevdat on rpev
drop index rpevifsm on rpevifsm
drop index rpevinb on rpevinb
drop index rpevinbp on rpevinbp
drop index rpevitm on rpev
drop index rpevjep on rpevjep
drop index rpevloc on rpev
drop index rpevl01 on rpevl01
drop index rpevmbl on rpevmbl
drop index rpevo on rpevo
drop index rpevpck on rpevpck
drop index rpevpick on rpevpick
drop index rpevplcd on rpevplcd
drop index rpevplt on rpev
drop index rpevrcl on rpevrcl
drop index rpevrec on rpevrec
drop index rpevstr on rpev
drop index rpevt on rpevt
drop index rpevtag on rpev
drop index rpevtg1 on rpevtg1
drop index rpevtprt on rpevtprt
drop index rpevtsk on rpev
drop index rpevtsko on rpevo
drop index rpevttas on rpevt
drop index rpevwork on rpevwork
drop index rpevx on rpevx
drop index rpev01 on rpev
drop index rpev02 on rpev02
drop index rpev03 on rpev
drop index rpev04 on rpev
drop index rpev06 on rpev
drop index rpmb on rpmb
drop index rpmbdt on rpmb
drop index rpmn on rpmn
drop index rpmw on rpmw
drop index rpnd on rpnd
drop index rprxara on rprx
drop index rprxdor on rprx
drop index rprxupd on rprx
drop index rpshl01 on rpsh
drop index rpshl02 on rpsh
drop index rpshl03 on rpsh
drop index rpshpty on rpshpty
drop index rpshusr on rpshusr
drop index rpywrkm on rpywrkm
drop index rpywrkw on rpywrkw
drop index rrbl on rrbl
drop index rrbldat on rrbl
drop index rrblo on rrblo
drop index rrpl on rrpl
drop index rrpldft on rrpl
drop index rrplpri on rrplpri
drop index rsop on rsop
drop index rsopx on rsopx
drop index rsop2 on rsop2
drop index rsop3 on rsop3
drop index rsop4l1 on rsop4
drop index rspl on rspl
drop index rstd on rstd
drop index rstr on rstr
drop index rstrnm1 on rstr
drop index rstrx on rstrx
drop index rs4desl1 on rs4des
drop index rtem on rtem
drop index rtemdsc on rtem
drop index rtemx on rtemx
drop index rtgdsc on rtgdsc
drop index rtgtbl on rtgtbl
drop index rtgtblal on rtgtblal
drop index rtgtblcn on rtgtblcn
drop index rtgtbllu on rtgtbl
drop index rtgtblst on rtgtblst
drop index rtgtblzp on rtgtblzp
drop index rtim on rtim
drop index rtlc on rtlc
drop index rtlctrk on rtlc
drop index rtpr on rtpr
drop index rtrv on rtrv
drop index rtsk on rtsk
drop index rtskasni on rtskasni
drop index rtskbld on rtsk
drop index rtskemp on rtsk
drop index rtsko on rtsko
drop index rtskotb on rtsk
drop index rtsksch on rtsk
drop index rtsksdt on rtsk
drop index rtskseq on rtsk
drop index rtskstg on rtsk
drop index rtskstr on rtsk
drop index rtsktss on rtsk
drop index rwferr on rwferr
drop index rwfpmr on rwfpmr
drop index ryndwn on ryndwn
drop index sboll01 on sbol
drop index sbsendfile on sbsendfile
drop index sbsfile on sbsfile
drop index scactp on scactp
drop index scbldfl1 on scbldf
drop index scofixl1 on scofixp
drop index scofixl2 on scofixp
drop index scordfl1 on scordf
drop index scordfl2 on scordf
drop index scout14f on scout14f
drop index scpctlfl on scpctlfl
drop index scst on scst
drop index scstbld on scst
drop index scstcrp1 on scst
drop index scstper on scst
drop index scststr on scst
drop index scstz on scst
drop index scvnamf on scvnamf
drop index scvstr on scvstr
drop index scwlotlf on scwlotlf
drop index scwlotpf on scwlotpf
drop index sext on sext
drop index sextall on sext
drop index sgrp on sgrp
drop index sgrpnam on sgrp
drop index sinvtbl on sinvtbl
drop index sitm on sitm
drop index slci on slci
drop index slcn on slcn
drop index slcnascend on slcnascend
drop index slcndescnd on slcndescnd
drop index slcndor on slcn
drop index slcndorx on slcndorx
drop index slcndr2 on slcn
drop index slcndr3 on slcn
drop index slcndr3x on slcndr3x
drop index slcnlvl on slcn
drop index slcnrow on slcn
drop index slcnspc on slcnspc
drop index slcnstg on slcnstg
drop index slcnstgrow on slcnstgrow
drop index slcnstgx on slcnstgx
drop index slcnstg2 on slcnstg2
drop index sloc on sloc
drop index slot on slot
drop index sltldirstg on sltldirstg
drop index soloobpl1 on soloobp
drop index soloobpl2 on soloobp
drop index soloock on soloock
drop index soloxrf on soloxrf
drop index spchrgf on spchrgf
drop index spchrgfa on spchrgf
drop index spchrgfc on spchrgf
drop index spchrgfi on spchrgf
drop index spchrgfl on spchrgf
drop index spchrgfs on spchrgf
drop index spchrgft on spchrgf
drop index spctab on spctab
drop index spctot on spctot
drop index spcwrk on spcwrk
drop index spgm on spgm
drop index sprf on sprf
drop index sprflf1 on sprf
drop index sprflf2 on sprf
drop index srebld on srebld
drop index stamp on stamp
drop index stbl on stbl
drop index stdwrk on stdwrk
drop index stkchgpf on stkchgpf
drop index straud on straud
drop index strnum on strnum
drop index strrtg on strrtg
drop index strtxt on strtxt
drop index stscx on stscx
drop index stsdx on stsdx
drop index stsmx on stsmx
drop index stswx on stswx
drop index sts870all on sts870p
drop index sts870l on sts870l
drop index sts870l1 on sts870p
drop index stvday on stvday
drop index stvdayl1 on stvday
drop index stvdayl2 on stvday
drop index stvdayl3 on stvday
drop index stvdayp on stvdayp
drop index stvrate on stvrate
drop index stvtemp on stvtemp
drop index stvtmpl1 on stvtemp
drop index stvwk120 on workday
drop index stvwrk on stvwrk
drop index stvwrkl2 on stvwrk
drop index stvwrkl3 on stvwrk
drop index stvwrkl5 on stvwrk
drop index stvz on stvz
drop index stv2rate on stv2rate
drop index styp on styp
drop index suhstl1 on suhst
drop index sundat on sundat
drop index swapitm on swapitm
drop index swbat on swbat
drop index swext on swext
drop index swlcn on swlcn
drop index swlcnbat on swlcn
drop index swlcnord on swlcn
drop index swlcnpck on swlcnpck
drop index swlcnstr on swlcnstr
drop index swptnr on swptnr
drop index swptp on swptp
drop index syscmdaut on syscmdaut
drop index sysopt on sysopt
drop index tacmt on tacmt
drop index talc on talc
drop index talcdsq on talc
drop index talcloc on talc
drop index talclsq on talc
drop index talcmrg on talc
drop index talcomg on talc
drop index talcpck on talcpck
drop index talcpst on talc
drop index talcrcl on talc
drop index talctag on talc
drop index tanups on tanups
drop index tanups1 on tanups
drop index tanups2 on tanups
drop index tanups3 on tanups
drop index tanups4 on tanups
drop index tapp on tapp
drop index tapt on tapt
drop index taptdat on tapt
drop index tasn on tasn
drop index tasnext on tasn
drop index tasnitm on tasn
drop index tasnlot on tasn
drop index tasnnpln on tasnnpln
drop index tasnpck on tasn
drop index tasnpln on tasnpln
drop index tasntag on tasn
drop index tasnx on tasnx
drop index taswnpln on taswnpln
drop index taswpck on tasw
drop index taswpln on taswpln
drop index taswsrl on tasw
drop index tcal on tcal
drop index tcbw on tcbw
drop index tchg on tchg
drop index tchgpro on tchg
drop index tcmm on tcmm
drop index tcmml2 on tcmml2
drop index tcmml3 on tcmm
drop index tcmml4 on tcmm
drop index tcmml5 on tcmm
drop index tcmt on tcmt
drop index tcmtpc on tcmt
drop index tcnm on tcnm
drop index tcom on tcom
drop index tctl on tctl
drop index tctlagt on tctl
drop index tctlbld on tctlbld
drop index tctlbrf on tctl
drop index tctlbrfq on tctl
drop index tctlcar1 on tctl
drop index tctlcar2 on tctl
drop index tctlcasc on tctl
drop index tctlcng on tctlcng
drop index tctlcnr on tctlcnr
drop index tctlcon on tctl
drop index tctlconq on tctl
drop index tctldat on tctl
drop index tctldocm on tctldocm
drop index tctldocw on tctldocw
drop index tctldst on tctldst
drop index tctldst1 on tctldst1
drop index tctldst2 on tctldst2
drop index tctlent on tctlent
drop index tctleom on tctl
drop index tctlext on tctlext
drop index tctllbr on tctl
drop index tctlmbl on tctl
drop index tctlmlk on tctl
drop index tctlo on tctlo
drop index tctlpck on tctlpck
drop index tctlq on tctl
drop index tctlref on tctl
drop index tctlrefm on tctlrefm
drop index tctlrefq on tctl
drop index tctlrefs on tctlrefs
drop index tctlrefw on tctlrefw
drop index tctlsch on tctlsch
drop index tctlsid on tctl
drop index tctlspl on tctl
drop index tctlstr on tctl
drop index tctlstro on tctlo
drop index tctlstrq on tctl
drop index tctlusr on tctl
drop index tctl02 on tctl
drop index tctl1 on tctl
drop index tdac on tdac
drop index tdacdat on tdac
drop index tdacldt on tdac
drop index tdaclod on tdac
drop index tdaclon on tdaclon
drop index tdactim on tdac
drop index tdhw on tdhw
drop index tdlv on tdlv
drop index tdtl on tdtl
drop index tdtm on tdtm
drop index tdtmcng on tdtmcng
drop index tdtmdat on tdtm
drop index tdtmdlv on tdtm
drop index tdtmdrv on tdtm
drop index tdtmupd on tdtm
drop index tdtmupd1 on tdtmupd1
drop index tdwtran on tdwtran
drop index texc on texc
drop index texcstr on texc
drop index texr on texr
drop index texrlnk on texr
drop index texrmbl on texr
drop index texro on texro
drop index texrsref on texr
drop index texr2 on texr2
drop index texr2l1 on texr2
drop index texr2l2 on texr2
drop index texr2l4 on texr2
drop index texr2q on texr2
drop index tfrt on tfrt
drop index tfrtpro on tfrt
drop index tfrtshp on tfrt
drop index tikl on tikl
drop index tillwrk on tillwrk
drop index tinb on tinb
drop index tinbdat on tinb
drop index tinbdt on tinb
drop index tinbstr on tinb
drop index tinbsts on tinb
drop index tinv on tinv
drop index tinvplt on tinv
drop index titm on titm
drop index titmdcms on titm
drop index titmdcws on titm
drop index titmdocm on titm
drop index titmdocw on titm
drop index titmlot on titm
drop index titml01 on titm
drop index titmo on titmo
drop index titmpck on titmpck
drop index titmpdoc on titm
drop index titmrefm on titm
drop index titmrefw on titm
drop index titmrfms on titm
drop index titmrfws on titm
drop index titmstr on titm
drop index titmstro on titmo
drop index titmx on titmx
drop index titmxchk on titmxchk
drop index titx on titx
drop index titxdoc on titx
drop index tjlwrk on tjlwrk
drop index tkfile on tkfile
drop index tla on tlcn
drop index tlcn on tlcn
drop index tlcnact on tlcn
drop index tlcnalc on tlcn
drop index tlcndat on tlcn
drop index tlcndlc on tlcn
drop index tlcndoc on tlcn
drop index tlcndtl on tlcn
drop index tlcnfix on tlcn
drop index tlcnhld on tlcnhld
drop index tlcnhol on tlcn
drop index tlcnibd on tlcn
drop index tlcnibs on tlcn
drop index tlcnill on tlcn
drop index tlcninb on tlcn
drop index tlcninl on tlcn
drop index tlcnitg on tlcn
drop index tlcnitm on tlcn
drop index tlcnitxj on tlcnitxj
drop index tlcnitx3 on tlcnitx3
drop index tlcnit2 on tlcnit2
drop index tlcnloc on tlcn
drop index tlcnloc2 on tlcn
drop index tlcnlot on tlcn
drop index tlcnlotw on tlcnw
drop index tlcnltq on tlcn
drop index tlcnlts on tlcn
drop index tlcnlvl on tlcn
drop index tlcno on tlcno
drop index tlcnord on tlcn
drop index tlcnphy on tlcn
drop index tlcnpk1 on tlcn
drop index tlcnpk2 on tlcn
drop index tlcnplt on tlcn
drop index tlcnpur on tlcn
drop index tlcnrow on tlcn
drop index tlcnsil on tlcn
drop index tlcnsilp on tlcn
drop index tlcnsil2 on tlcn
drop index tlcnsil2w on tlcnw
drop index tlcnstg on tlcn
drop index tlcnsti on tlcn
drop index tlcnst2 on tlcn
drop index tlcnst3 on tlcn
drop index tlcnst4 on tlcn
drop index tlcntag on tlcn
drop index tlcntag5x on tlcn
drop index tlcntal on tlcn
drop index tlcntds on tlcn
drop index tlcntgs on tlcn
drop index tlcntg2 on tlcntg2
drop index tlcntlt on tlcn
drop index tlcnw on tlcnw
drop index tlcn01 on tlcn
drop index tlcn02 on tlcn
drop index tlelj01 on tlelj01
drop index tlod on tlod
drop index tloddrv on tlod
drop index tloddsp on tlod
drop index tlodpf on tlod
drop index tlodzne on tlod
drop index tlot on tlot
drop index tlotdsq on tlot
drop index tlotosq on tlot
drop index tmbd on tmbd
drop index tmbh on tmbh
drop index tmblchg on tmblchg
drop index tmblcmt on tmblcmt
drop index tmbldtl on tmbldtl
drop index tmblhdr on tmblhdr
drop index tmblpro on tmblpro
drop index tmbp on tmbp
drop index tmbs on tmbs
drop index tmfc on tmfc
drop index tmfcpc on tmfc
drop index tmid on tmid
drop index tmih on tmih
drop index tmihar# on tmih
drop index tmihari on tmih
drop index tmihaud on tmih
drop index tmihcst on tmih
drop index tmihpro on tmih
drop index tmsc on tmsc
drop index tnam on tnam
drop index toivcd on toivcd
drop index toivch on toivch
drop index toms on toms
drop index tomsstr on toms
drop index tood on tood
drop index toodlod on tood
drop index toodmnt on tood
drop index toodper on tood
drop index toos on toos
drop index toosper on toos
drop index toravc on toravc
drop index toravd on toravd
drop index toravh on toravh
drop index tosavc on tosavc
drop index tosavd on tosavd
drop index tosavh on tosavh
drop index tosd on tosd
drop index tosdlod on tosd
drop index tpadl1 on tpad
drop index tpck on tpck
drop index tpka on tpka
drop index tpkd on tpkd
drop index tpkdcar on tpkd
drop index tpkdcas on tpkd
drop index tpkdcng on tpkd
drop index tpkdcsp on tpkd
drop index tpkddoc on tpkd
drop index tpkddoco on tpkdo
drop index tpkdhrs on tpkd
drop index tpkdlin on tpkd
drop index tpkdmnf on tpkd
drop index tpkdo on tpkdo
drop index tpkdplt on tpkd
drop index tpkdpty on tpkd
drop index tpkdref on tpkd
drop index tpkdtyp on tpkd
drop index tpkdwav on tpkd
drop index tpkh on tpkh
drop index tpkhpty on tpkh
drop index tpki on tpki
drop index tpkm on tpkm
drop index tpkmdat on tpkm
drop index tpko on tpko
drop index tpkobat on tpko
drop index tpkobdt on tpko
drop index tpkobld on tpko
drop index tpkobst on tpko
drop index tpkodat on tpko
drop index tpkohbl on tpkohbl
drop index tpkohbs on tpkohbs
drop index tpkohdt on tpkohdt
drop index tpkohsd on tpkohsd
drop index tpkohst on tpkohst
drop index tpkoloc on tpko
drop index tpkoo on tpkoo
drop index tpkosdt on tpko
drop index tpkosts on tpko
drop index tpkw on tpkw
drop index tplc on tplc
drop index tplh on tplh
drop index tplm on tplm
drop index tplt on tplt
drop index tplx on tplx
drop index tpol on tpol
drop index tpra on tpra
drop index tprf on tprf
drop index tprfz on tprfz
drop index tpro on tpro
drop index tproapp on tproapp
drop index tproapt on tproapt
drop index tprobrf on tpro
drop index tprocng on tpro
drop index tprocrf on tpro
drop index tprodat on tpro
drop index tprodrv on tpro
drop index tproent on tpro
drop index tproinv on tproinv
drop index tprolod on tpro
drop index tpropol on tpropol
drop index tpropos on tpropos
drop index tproshp on tpro
drop index tprosh2 on tprosh2
drop index tprosh3 on tpro
drop index tprosrf on tpro
drop index tprostr on tpro
drop index tprx on tprx
drop index tpsd on tpsd
drop index tpsh on tpsh
drop index trcn on trcn
drop index trcr on trcr
drop index trct on trct
drop index trkddmf on trkddmf
drop index trls on trls
drop index trntbl on trntbl
drop index tsbp on tsbp
drop index tshl on tshl
drop index tshlmbl on tshl
drop index tshlmbo on tshl
drop index tssn on tssn
drop index tstd on tstd
drop index tstf on tstf
drop index tsts on tsts
drop index tstshst on tstshst
drop index tstsinv on tsts
drop index tstsstd on tsts
drop index tstssts on tsts
drop index tstw on tstw
drop index tstwpl1 on tstw
drop index tstwpol on tstw
drop index ttfd on ttfd
drop index ttfm on ttfm
drop index ttfmlf on ttfm
drop index ttrc on ttrc
drop index ttrcact on ttrc
drop index ttrctim on ttrc
drop index ttsk on ttsk
drop index ttskcrp on ttskcrp
drop index ttsknbr on ttsknbr
drop index ttskord on ttskord
drop index ttskseq on ttskseq
drop index tunt on tunt
drop index twal on twal
drop index uacb on uacb
drop index uacf on uacf
drop index uacfl1 on uacfl1
drop index uapl on uapl
drop index uaplnam on uapl
drop index uitm on uitm
drop index uitmloc on uitm
drop index ulcn on ulcn
drop index upcdow on upcdow
drop index upcmvobj on upcmvobj
drop index upstrx on upstrx
drop index upxlscpy1 on upxlscpy1
drop index upxlsf1 on upxlsf1
drop index uref on uref
drop index userpf on userpf
drop index ustsh on ustsh
drop index ustshstp# on ustsh
drop index utbl on utbl
drop index vblm on vblm
drop index vccsddoc on vccsd
drop index vccsdl01 on vccsd
drop index vccsdl02 on vccsd
drop index vccsdl03 on vccsd
drop index vccshl01 on vccsh
drop index wara on wara
drop index waraara on wara
drop index warc on warc
drop index warcnam on warc
drop index wasn on wasn
drop index wasncn on wasn
drop index wasnmd on wasn
drop index wasnmd2 on wasn
drop index wbat on wbat
drop index wbatusr on wbat
drop index wbcr on wbcr
drop index wbld on wbld
drop index wcag on wcag
drop index wcagitm on wcag
drop index wcat on wcat
drop index wcgrp on wcgrp
drop index wcng on wcng
drop index wcngadr on wcng
drop index wcngnam on wcng
drop index wcom on wcom
drop index wcoml1 on wcom
drop index wcoml2 on wcoml2
drop index wcomnum on wcom
drop index wcpm on wcpm
drop index wdsc on wdsc
drop index wdsclms on wdsc
drop index wdscmsg on wdscmsg
drop index wdscmsr on wdscmsr
drop index wdscold on wdscold
drop index wdsctsk on wdsctsk
drop index wdwn on wdwn
drop index weom on weom
drop index weomarc on weom
drop index weomnam on weom
drop index weomnm1 on weom
drop index weomoar on weom
drop index weomowr on weom
drop index weomrwr on weom
drop index weomstr on weom
drop index weqp on weqp
drop index wftask on wftask
drop index whdt on whdt
drop index whdtsub on whdt
drop index whdt01 on whdt
drop index whdt02 on whdt
drop index whdt03 on whdt
drop index whdt04 on whdt
drop index whdt05 on whdt05
drop index whdt06 on whdt06
drop index whdt07 on whdt07
drop index whdt08 on whdt08
drop index whdt09 on whdt
drop index whdt10 on whdt10
drop index whiadj on whiadj
drop index whiadj01 on whiadj
drop index whirex on whirex
drop index whirls on whirls
drop index whirls01 on whirls01
drop index whirls02 on whirls02
drop index whirls03 on whirls03
drop index whirls04 on whirls04
drop index whjcsflr on whjcsflr
drop index whjcsflr01 on whjcsflr01
drop index whjcsflr02 on whjcsflr02
drop index whjcsflr03 on whjcsflr03
drop index whjcsrck on whjcsrck
drop index whjcsrck01 on whjcsrck01
drop index whjcsrck02 on whjcsrck02
drop index whjcsrck03 on whjcsrck03
drop index whjemflr on whjemflr
drop index whjemflr01 on whjemflr01
drop index whjemflr02 on whjemflr02
drop index whjemflr03 on whjemflr03
drop index whjemrck on whjemrck
drop index whjemrck01 on whjemrck01
drop index whjemrck02 on whjemrck02
drop index whjemrck03 on whjemrck03
drop index whjwkact01 on whjwkact01
drop index whjwkact03 on whjwkact03
drop index whlactbl01 on whpactbl
drop index whlactgr01 on whpactgr
drop index whlactgr02 on whpactgr
drop index whlactgr03 on whpactgr
drop index whlactgr04 on whpactgr
drop index whlacuts01 on whpacuts
drop index whlbolms on whpbolms
drop index whlcalca01 on whpcalca
drop index whlcalca02 on whpcalca
drop index whlcalca03 on whpcalca
drop index whlcalio01 on whpcalio
drop index whlcalio02 on whpcalio
drop index whlcalio03 on whpcalio
drop index whlcalio04 on whpcalio
drop index whlcalio05 on whlcalio05
drop index whlcalio06 on whpcalio
drop index whlcalio07 on whpcalio
drop index whlcalms01 on whpcalms
drop index whlcalup01 on whpcalup
drop index whldchka01 on whpdchka
drop index whldchka02 on whpdchka
drop index whldchka03 on whpdchka
drop index whldchka04 on whpdchka
drop index whldchkq01 on whpdchkq
drop index whldchkq02 on whldchkq02
drop index whldchks01 on whpdchks
drop index whldchks02 on whpdchks
drop index whldoorm1 on whpdoorm
drop index whldpcshgt on iit888
drop index whldpxrf01 on whpdpxrf
drop index whldpxrf02 on whpdpxrf
drop index whljbahd01 on whpjbahd
drop index whljbahd02 on whpjbahd
drop index whljbavg01 on whpjbavg
drop index whljbavg02 on whpjbavg
drop index whllckin01 on whplckin
drop index whlovdch01 on whpovdch
drop index whlovdch02 on whpovdch
drop index whlovdch03 on whpovdch
drop index whlrsnac01 on whprsnac
drop index whlrsncd01 on whprsncd
drop index whlwkact02 on whpwkact
drop index whlwrklc01 on whpwrklc
drop index whlznstg01 on whpznstg
drop index whlznstg02 on whlznstg02
drop index whlznstg03 on whlznstg03
drop index whlznstg04 on whpznstg
drop index whlznstg05 on whpznstg
drop index whl888d1 on whp888d
drop index whl888h1 on whl888h1
drop index whl888h2 on whp888h
drop index whpactbl on whpactbl
drop index whpbldng on whpbldng
drop index whpcalca on whpcalca
drop index whpcalms on whpcalms
drop index whpcalsh on whpcalsh
drop index whpcalup on whpcalup
drop index whpcmplx on whpcmplx
drop index whpdoorm on whpdoorm
drop index whpdorgr on whpdorgr
drop index whphlday on whphlday
drop index whpjbfun on whpjbfun
drop index whpkrcl01 on whpkrcl01
drop index whpkrcl02 on whpkrcl02
drop index whplddft on whplddft
drop index whpldtpm on whpldtpm
drop index whplocms on whplocms
drop index whprsnct on whprsnct
drop index whpstged on whpstged
drop index whpuomms on whpuomms
drop index whpwkact on whpwkact
drop index whpyrdms on whpyrdms
drop index whpzonem on whpzonem
drop index whse on whse
drop index whsinbd on whsinbd
drop index whtext on whtext
drop index winv on winv
drop index wisl on wisl
drop index witm on witm
drop index witmcas on witm
drop index witmitm2 on witm
drop index witmloc on witm
drop index witmlocd on witm
drop index witmnam on witm
drop index witmnmf on witm
drop index witmpck on witmpck
drop index witmpsu on witm
drop index witmsav on witmsav
drop index witmsub on witm
drop index witmupc on witm
drop index witm0f on witm
drop index witm07 on witm
drop index witm2 on witm2
drop index witm2bom on witm2
drop index witm2cst on witm2
drop index witm2upc on witm2
drop index witx on witx
drop index wjas on wjas
drop index wjas01 on wjas
drop index wjas02 on wjas
drop index wjas03 on wjas
drop index wjas04 on wjas
drop index wkasnd on wkasnd
drop index wkasnh on wkasnh
drop index wkfile on wkfile
drop index wklot on wklot
drop index wkrecalp on wkrecalp
drop index wkrecl on wkrecl
drop index wkrpev on wkrpev
drop index wlcn on wlcn
drop index wlcnaia on wlcn
drop index wlcnalv on wlcn
drop index wlcnara on wlcn
drop index wlcnarc on wlcn
drop index wlcnbap on wlcnbap
drop index wlcndar on wlcn
drop index wlcndlv on wlcn
drop index wlcnlvl on wlcn
drop index wlcnrow on wlcn
drop index wlcntpc on wlcn
drop index wloc on wloc
drop index wlocdlv on wlocdlv
drop index wlocdtl on wlocdtl
drop index wlot on wlot
drop index wlotloc on wlot
drop index wlotlocd on wlot
drop index wlotnam on wlot
drop index wlotpb on wlotpb
drop index wlotsav on wlotsav
drop index wlotsit on wlot
drop index wlotsub on wlot
drop index wlpp01 on wlpp
drop index wmh1 on wmh1
drop index wmh101 on wmh1
drop index wmh102 on wmh1
drop index wmh103 on wmh1
drop index wmh104 on wmh1
drop index wmh2 on wmh2
drop index wmh201 on wmh2
drop index wmh202 on wmh2
drop index wmh203 on wmh203
drop index wmh3 on wmh3
drop index wmh301 on wmh3
drop index wmh302 on wmh3
drop index wmh303 on wmh3
drop index wmh304 on wmh3
drop index wmh305 on wmh3
drop index wmh306 on wmh306
drop index wmh307 on wmh307
drop index wmh4 on wmh4
drop index wmh401 on wmh4
drop index wmpr on wmpr
drop index wmsk on wmsk
drop index wmsmsgpf on wmsmsgpf
drop index wmstbll1 on wmstbl
drop index wmstbll2 on wmstbl
drop index wmstbll3 on wmstbl
drop index wmstdsl1 on wmstds
drop index wms103al1 on wms103a
drop index wms103al10 on wms103al10
drop index wms103al11 on wms103al11
drop index wms103al2 on wms103a
drop index wms103al3 on wms103al3
drop index wms103al4 on wms103a
drop index wms103al5 on wms103a
drop index wms103al6 on wms103a
drop index wms103al7 on wms103a
drop index wms103al8 on wms103al8
drop index wms103al9 on wms103al9
drop index wnam on wnam
drop index wnamcde on wnamcde
drop index wnamnam on wnam
drop index wnamnamt on wnamnamt
drop index wnamnbrt on wnamnbrt
drop index wnamsav on wnamsav
drop index wnbr on wnbr
drop index wn98inb on wn98
drop index wn98loc on wn98
drop index wopt on wopt
drop index workday on workday
drop index wplq on wplq
drop index wprf on wprf
drop index wprfnet on wprf
drop index wprfrev on wprf
drop index wprx on wprx
drop index wpshais on wpshais
drop index wpshbwd on wpsh
drop index wpshitm on wpsh
drop index wpshjep on wpsh
drop index wpshlsi on wpshlsi
drop index wpshpkl on wpsh
drop index wpshpla on wpshpla
drop index wpshpld on wpshpld
drop index wpshrev on wpsh
drop index wpshslk on wpshslk
drop index wpshtag on wpsh
drop index wpshtgi on wpsh
drop index wpshusr on wpsh
drop index wps2 on wps2
drop index wptc on wptc
drop index wque on wque
drop index wqueaaq on wque
drop index wqueabq on wque
drop index wqueitm on wque
drop index wrau on wrau
drop index wrclnblh on wrclnblh
drop index wrcmvbl1 on wrcmvbf
drop index wrcmvwl1 on wrcmvwf
drop index wrc2 on wrc2
drop index wreq on wreq
drop index wrev on wrev
drop index wrevadj on wrev
drop index wrevdat on wrev
drop index wrevinv on wrevinv
drop index wrevopn on wrevopn
drop index wrevper on wrev
drop index wrevstr on wrev
drop index wrevxxx on wrevxxx
drop index wrhld on wrhld
drop index wrhrls on wrhrls
drop index wrkact on wrkact
drop index wrkac2 on wrkac2
drop index wrkctl on wrkctl
drop index wrkfil on wrkfil
drop index wrklcn on wrklcn
drop index wrkloc on wrkloc
drop index wrklod on wrklod
drop index wrkmbl on wrkmbl
drop index wrkord on wrkord
drop index wrkpck on wrkpck
drop index wrkphy on wrkphy
drop index wrpltl1 on wrplt
drop index wrpltl2 on wrplt
drop index wrplt2l1 on wrplt2
drop index wscn on wscn
drop index wsel on wsel
drop index wsls on wsls
drop index wssp on wssp
drop index wstr on wstr
drop index wstrarc on wstr
drop index wstrcls on wstrcls
drop index wstrgrp on wstr
drop index wstrloc on wstr
drop index wstrlocn on wstr
drop index wstrnam on wstr
drop index wstrsav on wstrsav
drop index wstr214 on wstr
drop index wsts on wsts
drop index wsub on wsub
drop index wsublf1 on wsub
drop index wtag on wtag
drop index wtaudd on wtaudd
drop index wtauddl1 on wtaudd
drop index wtauddl2 on wtaudd
drop index wtauddl3 on wtaudd
drop index wtauddl4 on wtaudd
drop index wtaudh on wtaudh
drop index wtaudhl1 on wtaudh
drop index wtaudhl2 on wtaudh
drop index wtaudhl3 on wtaudh
drop index wtaudhl4 on wtaudhl4
drop index wtaudhl5 on wtaudhl5
drop index wtaudhl6 on wtaudhl6
drop index wtaudhl7 on wtaudhl7
drop index wtaudhl8 on wtaudh
drop index wtbl on wtbl
drop index wtbl03 on wtbl03
drop index wtprowk on wtprowk
drop index wtsk on wtsk
drop index wtskhdl on wtskhdl
drop index wtsknbr on wtsk
drop index wups on wups
drop index wusr on wusr
drop index wusrclk on wusr
drop index wusrgrp on wusr
drop index wusrloc on wusr
drop index wusrnam on wusr
drop index wusrnm1 on wusrnm1
drop index wusrpsw on wusr
drop index wvnd on wvnd
drop index wxpt on wxpt
drop index wxrf on wxrf
drop index wxrfdsc on wxrf
drop index xafile on xafile
drop index xlcn on xlcn
drop index xrftbl on xrftbl
drop index yapd on yapd
drop index ycfg on ycfg
drop index ydrvsum on ydrvsum
drop index yhstwrk on yhstwrk
drop index yitm on yitm
drop index ylcn on ylcn
drop index ylcnlcn on ylcn
drop index ypev on ypev
drop index ypevitm on ypev
drop index ypevit2 on ypev
drop index ypevtag on ypev
drop index ypro on ypro
drop index yscprpt on yscprpt
drop index yscwcdr on yscwrk
drop index yscwcsh on yscwrk
drop index yscwrk on yscwrk
drop index zacttsk on zacttsk
drop index zbil on zbil
drop index zbilfrt on zbil
drop index zcngitmd on zcngitms
drop index zcngitmr on zcngitms
drop index zcngitms on zcngitms
drop index zcngrnk on zcngrnk
drop index zcngrnkd on zcngrnk
drop index zcngrnkp on zcngrnk
drop index zcngrnks on zcngrnk
drop index zcngstr on zcngstr
drop index zcngstrs on zcngstr
drop index zcngsum on zcngsum
drop index zcnlwrk on zcnlwrk
drop index zctl on zctl
drop index zgrp on zgrp
drop index zgrpanl on zgrp
drop index zgrprnk on zgrp
drop index zgrprn1 on zgrp
drop index zhst on zhst
drop index zhstgwy on zhst
drop index zhstloc on zhst
drop index zhststr on zhst
drop index zitmdoc on zitmdoc
drop index zitmpck on zitmdoc
drop index zitmplsq on zitmplsq
drop index zitmseq on zitmwrk
drop index zitmsub on zitmwrk
drop index zitmwrk on zitmwrk
drop index zlbr on zlbr
drop index zlbrlemp on zlbr
drop index zlcn on zlcn
drop index zlcnitm on zlcn
drop index zlcnlcn on zlcn
drop index zlotwrk on zlotwrk
drop index zmid on zmid
drop index zpksrta on zpksrta
drop index zprf on zprf
drop index zpro on zpro
drop index zproaps on zproaps
drop index zprocng on zprocng
drop index zproshp on zproshp
drop index zprozip on zprozip
drop index zrev on zrev
drop index zrevac on zrev
drop index zrevact on zrevact
drop index zrevdwn on zrevdwn
drop index zscpsls on zscpsls
drop index zstraspn on zstraspn
drop index zstrbld on zstraspn
drop index zxrfwrk on zxrfwrk
drop index zzipstr on zzipstr
drop index zzlicvlc01 on zzpicvlc
drop index zzlicvlc02 on zzpicvlc
drop index zzlmndty01 on zzpmndty
drop index zznl on zznl
drop index zzpcasrep on zzpcasrep
drop index zzpexctl on zzpexctl
drop index zzpexloa on zzpexloa
drop index zzpexlog on zzpexlog
drop index zzpicvxr on zzpicvxr
drop index zzpimnmx on zzpimnmx
drop index zzpmgcus on zzpmgcus
drop index zzppesdo on zzppesdo
drop index zzppessb on zzppessb
drop index zzppotos on zzppotos
drop index zzpshpob on zzpshpob
drop index zzpshpst on zzpshpst
drop index zzptrlod on zzptrlod
drop index z550611 on z550611
drop index eshnl01 on eshn
drop index eshnl02 on eshn
drop index osavh on osavh
drop index dscdta on dscdta
drop index dtnbr1 on dtnbr1
drop index icpqhld29 on icpqhld29
drop index intdta on intdta
drop index pinvy on pinvy
